## \*\*Задание на повторение материала

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [2]:
import numpy as np

a = np.arange(12, 24, 1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [9]:
print(a.reshape((2,6)))
print(a.reshape((3,4)))
print(a.reshape((4,3)))
print(a.reshape((6,2)))
print(a.reshape((12,1)))


[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [11]:
print(a.reshape((2,-1)))
print(a.reshape((3,-1)))
print(a.reshape((4,-1)))
print(a.reshape((-1,2)))
print(a.reshape((-1,1)))

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Нет. Это матрица с одним столбцом.

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [37]:
a = np.array([np.random.normal() for x in range(1,13)]).reshape((3, 4))
print(a)
print(a.reshape((1,-1)))

[[ 0.5046587  -0.22778864  1.95317165 -0.43621054]
 [-1.45577472  0.66656966 -0.83902698 -0.57525381]
 [ 0.27481148 -0.16147216  2.06787466 -0.44309775]]
[[ 0.5046587  -0.22778864  1.95317165 -0.43621054 -1.45577472  0.66656966
  -0.83902698 -0.57525381  0.27481148 -0.16147216  2.06787466 -0.44309775]]


6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [25]:
a = np.array([x for x in range(20,0,-2)])
print(a)

[20 18 16 14 12 10  8  6  4  2]


7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [28]:
b = a.reshape((-1,1))
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

Массив a - одномерный, b - двумерный.

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [53]:
b = np.ones((3,2))
print(f'b = {b}')
a = np.zeros((b.shape[0]-1,2))
print(f'a = {a}')
v = np.vstack((a,b))
print(f'v = {v}')
print(f'v.size = {v.size}')

b = [[1. 1.]
 [1. 1.]
 [1. 1.]]
a = [[0. 0.]
 [0. 0.]]
v = [[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
v.size = 10


In [54]:
9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

Object `почему` not found.


9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему

In [79]:
a = np.arange(0, 12)
print(f'a = {a}')
A = a.reshape((4,3))
print(f'A = {A}')
At = A.T
print(f'At = {At}')
B = A.dot(At)
print(f'B = {B}')
Bdet = np.linalg.det(B)
print(f'Определитель B: {Bdet}')
if not Bdet:
    print('Обратную матрицу невозможно вычислить')

a = [ 0  1  2  3  4  5  6  7  8  9 10 11]
A = [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
At = [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
B = [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Определитель B: 0.0
Обратную матрицу невозможно вычислить


10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [73]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [76]:
c = np.array([np.random.randint(0,16) for x in range(0,16)])
print(f'c = {c}')

c = [ 3  7  7  2  5  4  1  7 11 13  5  1 15 11  4  0]


12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [87]:
C = c.reshape((4,-1))
print(f'C = {C}')
D = 10*C + B
print(f'D = {D}')
print(f'det(D) = {np.linalg.det(D)}')
print(f'rank(D) = {np.linalg.matrix_rank(D)}')
D_inv = np.linalg.inv(D)
print(f'D_inv = {D_inv}')

C = [[ 3  7  7  2]
 [ 5  4  1  7]
 [11 13  5  1]
 [15 11  4  0]]
D = [[ 35  84  93  52]
 [ 64  90  96 192]
 [133 216 199 222]
 [182 232 252 302]]
det(D) = -23404999.999999978
rank(D) = 4
D_inv = [[-0.02745824 -0.02127921 -0.00030506  0.01848067]
 [-0.00983038 -0.00115445  0.03006537 -0.01967443]
 [ 0.03091391  0.00259603 -0.0266755   0.01263576]
 [-0.00169622  0.01154454 -0.00065371 -0.00325571]]


13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [101]:
D_inv = np.where(D_inv<0, 0, D_inv)
D_inv = np.where(D_inv>0, 1, D_inv)

#np.where(D_inv>0, 1, D_inv)
E = np.where(D_inv==0, C, B)
E


array([[  3,   7,   7,  32],
       [  5,   4,  86,   7],
       [ 23,  86,   5, 212],
       [ 15, 122,   4,   0]])